version: '3.4'
x-app-base: &app-base
  image: reachsh/reach-app-reach:latest
services:
  devnet:
    image: reachsh/ethereum-devnet:0.1
  algorand-devnet:
    image: reachsh/algorand-devnet:0.1
  reach-app-reach-ETH-test-dockerized-geth: &default-app
    <<: *app-base
    depends_on:
      - devnet
    environment:
      - REACH_CONNECTOR_MODE=ETH-test-dockerized-geth
      - ETH_NODE_URI=http://127.0.0.1:7545
  reach-app-reach-ETH-test-embedded-ganache:
    <<: *app-base
    environment:
      - REACH_CONNECTOR_MODE=ETH-test-embedded-ganache
  reach-app-reach-FAKE-test-embedded-mock:
    <<: *app-base
    environment:
      - REACH_CONNECTOR_MODE=FAKE-test-embedded-mock
  reach-app-reach-ALGO-test-dockerized-algod:
    <<: *app-base
    depends_on:
      - algorand-devnet
    environment:
      - REACH_CONNECTOR_MODE=ALGO-test-dockerized-algod
      - ALGO_SERVER=http://algorand-devnet
      - ALGO_PORT=4180
  reach-app-reach-: *default-app
  reach-app-reach: *default-app
  live:
    <<: *app-base
    environment:
      - ETH_NODE_URI=http://127.0.0.1:7545
  player: &player
    <<: *default-app
    stdin_open: true
  alice: *player 
  bob: *player